$(document).ready(function(){
  $('.sidenav').sidenav();
});
$(document).ready(function(){
  $('.collapsible').collapsible();
});
$(document).ready(function(){
  $('.modal').modal();
});
$(document).ready(function(){
  $('.scrollspy').scrollSpy();
});
$(document).ready(function(){
  $('.materialboxed').materialbox();
});
AOS.init({
  duration:2000,
});